"""Add foreign key booking-user

Revision ID: 89c5a60c2f95
Revises: fa4da53716da
Create Date: 2023-07-30 15:41:25.982340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c5a60c2f95'
down_revision = 'fa4da53716da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'booking', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    # ### end Alembic commands ###
