"""Add column 'service' to Room model

Revision ID: e6cbef14228f
Revises: d6a6286ae145
Create Date: 2023-07-29 13:15:42.781376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6cbef14228f'
down_revision = 'd6a6286ae145'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'services')
    # ### end Alembic commands ###
